# Generated by Django 5.2.8 on 2025-11-21 15:58

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название компонента')),
                ('component_type', models.CharField(choices=[('shop', 'Магазин'), ('blog', 'Блог'), ('gallery', 'Галерея'), ('contact', 'Контакты'), ('seo', 'SEO инструменты'), ('users', 'Управление пользователями'), ('other', 'Другое')], max_length=50, verbose_name='Тип компонента')),
                ('description', models.TextField(blank=True, verbose_name='Описание компонента')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Компонент',
                'verbose_name_plural': 'Компоненты',
            },
        ),
        migrations.CreateModel(
            name='ShopModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='RUB', max_length=10, verbose_name='Валюта')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Ставка налога (%)')),
                ('shipping_enabled', models.BooleanField(default=True, verbose_name='Включить доставку')),
                ('payment_methods', models.JSONField(default=list, verbose_name='Способы оплаты')),
                ('inventory_tracking', models.BooleanField(default=True, verbose_name='Отслеживание остатков')),
            ],
            options={
                'verbose_name': 'Модуль магазина',
                'verbose_name_plural': 'Модули магазина',
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название шаблона')),
                ('path', models.CharField(max_length=500, verbose_name='Путь к шаблону')),
                ('description', models.TextField(blank=True, verbose_name='Описание шаблона')),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='templates/previews/', verbose_name='Превью шаблона')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Шаблон',
                'verbose_name_plural': 'Шаблоны',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название товара')),
                ('slug', models.SlugField(max_length=200, verbose_name='URL-адрес')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание товара')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('stock', models.IntegerField(default=0, verbose_name='Количество на складе')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gubinnet.shopmodule', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название сайта')),
                ('domain', models.CharField(max_length=200, unique=True, verbose_name='Домен сайта')),
                ('template', models.CharField(default='default', max_length=200, verbose_name='Шаблон сайта')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец сайта')),
            ],
            options={
                'verbose_name': 'Сайт',
                'verbose_name_plural': 'Сайты',
            },
        ),
        migrations.AddField(
            model_name='shopmodule',
            name='site',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gubinnet.site', verbose_name='Сайт'),
        ),
        migrations.CreateModel(
            name='SeoSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='Заголовок (meta title)')),
                ('meta_description', models.TextField(blank=True, max_length=500, verbose_name='Описание (meta description)')),
                ('meta_keywords', models.CharField(blank=True, max_length=500, verbose_name='Ключевые слова (meta keywords)')),
                ('google_analytics', models.CharField(blank=True, max_length=100, verbose_name='Google Analytics ID')),
                ('yandex_metrika', models.CharField(blank=True, max_length=100, verbose_name='Yandex Metrika ID')),
                ('robots_txt', models.TextField(default='User-agent: *\nAllow: /', verbose_name='robots.txt')),
                ('sitemap', models.TextField(blank=True, verbose_name='Карта сайта')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gubinnet.site', verbose_name='Сайт')),
            ],
            options={
                'verbose_name': 'SEO настройки',
                'verbose_name_plural': 'SEO настройки',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок страницы')),
                ('slug', models.SlugField(max_length=200, verbose_name='URL-адрес')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Содержимое страницы')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gubinnet.site', verbose_name='Сайт')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
            },
        ),
        migrations.CreateModel(
            name='SiteComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config', models.JSONField(default=dict, verbose_name='Конфигурация компонента')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Включен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gubinnet.component', verbose_name='Компонент')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gubinnet.site', verbose_name='Сайт')),
            ],
            options={
                'verbose_name': 'Компонент сайта',
                'verbose_name_plural': 'Компоненты сайта',
            },
        ),
        migrations.CreateModel(
            name='UserManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_registration', models.BooleanField(default=True, verbose_name='Разрешить регистрацию')),
                ('require_email_verification', models.BooleanField(default=True, verbose_name='Требовать подтверждение email')),
                ('user_roles', models.JSONField(default=dict, verbose_name='Роли пользователей')),
                ('registration_fields', models.JSONField(default=list, verbose_name='Дополнительные поля регистрации')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gubinnet.site', verbose_name='Сайт')),
            ],
            options={
                'verbose_name': 'Управление пользователями',
                'verbose_name_plural': 'Управление пользователями',
            },
        ),
    ]
